name: Destroy OpenVPN Server

on:
  repository_dispatch:
    types: [destroy-vpn]

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.client_payload.region }}

      - name: Print selected region
        run: echo "Selected region is ${{ github.event.client_payload.region }}"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          echo "Initializing Terraform..."
          cd terraform
          terraform init
          echo "Terraform initialized successfully"

      - name: Terraform Destroy
        run: |
          echo "Destroying resources..."
          cd terraform
          terraform destroy -auto-approve \
           -var="region=${{ github.event.client_payload.region }}" \
           -var="ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}"
          echo "Terraform destroy completed"