name: Destroy OpenVPN Server

on:
  repository_dispatch:
    types: [destroy-vpn]

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.client_payload.region }}

      - name: Print selected region
        run: echo "Selected region is ${{ github.event.client_payload.region }}"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          echo "Initializing Terraform..."
          cd terraform
          terraform init
          echo "Terraform initialized successfully"

      - name: Terraform Destroy EC2
        run: |
          echo "Destroying EC2 only..."
          cd terraform
          terraform destroy -auto-approve \
            -target=aws_instance.VpnOpen_server \
            -target=aws_security_group.vpn_sg \
            -var="region=${{ github.event.client_payload.region }}" \
            -var="public_key=${{ secrets.SSH_PUBLIC_KEY }}"
          echo "EC2 destroyed"

      - name: Terraform Destroy SSH Key
        run: |
            echo "Destroying SSH Key..."
            cd terraform
            terraform destroy -auto-approve \
              -target=aws_key_pair.project_key \
              -var="region=${{ github.event.client_payload.region }}" \
              -var="public_key=${{ secrets.SSH_PUBLIC_KEY }}"
            echo "SSH Key destroyed"    